"""
xlwings Setup Helper for VistaDetail.xlsm.

Run this once to wire Python button handlers into the workbook:
    python -m vistadetail.setup_xlwings

What it does:
  1. Opens VistaDetail.xlsm via xlwings
  2. Injects VBA RunPython macros for each button (Generate, Clear, Export)
  3. Optionally installs the xlwings add-in if not already installed

Requirements:
  - Microsoft Excel must be installed and running (or will be launched)
  - xlwings add-in must be installed in Excel
    → Install via:  xlwings addin install
  - ANTHROPIC_API_KEY in environment (for AI notes; not required for generation)

After running this script, buttons in the Dashboard tab will call Python live.
"""

from __future__ import annotations

import os
import sys

def _find_workbook() -> str:
    base = os.path.join(os.path.dirname(__file__), "..")
    for name in ("Rebar Barlist Generator.xlsm", "Rebar Barlist Generator.xlsx",
                 "VistaDetail.xlsm", "VistaDetail.xlsx"):
        p = os.path.abspath(os.path.join(base, name))
        if os.path.exists(p):
            return p
    return os.path.abspath(os.path.join(base, "Rebar Barlist Generator.xlsm"))

WORKBOOK_PATH = _find_workbook()

# ---------------------------------------------------------------------------
# VBA code snippets injected into the workbook
# ---------------------------------------------------------------------------

_VBA_MODULE = """\
' VistaDetail Button Macros
' Auto-generated by vistadetail/setup_xlwings.py
' DO NOT EDIT MANUALLY — re-run setup_xlwings.py to regenerate
'
' NOTE: We use Application.Run "RunPython", "..." (late binding) instead of
' calling RunPython directly. This avoids the "Sub or Function not defined"
' compile error that occurs when xlwings.xlam is loaded as an add-in but is
' not set as an explicit VBA project reference.

Private Sub xRun(code As String)
    Application.Run "RunPython", code
End Sub

' ---------------------------------------------------------------------------
' SetupDropdowns — called from Workbook_Open in ThisWorkbook.
' Writes template names into _Templates col A, then wires a data-validation
' list on Dashboard!B3 referencing that range.
'
' The template list is EMBEDDED here as a VBA constant (comma-separated).
' This means it survives any Excel repair/reopen cycle — no dependency on
' openpyxl-written cell content.  Re-run setup_xlwings.py to update the list.
' ---------------------------------------------------------------------------
Sub SetupDropdowns()
    Dim ws      As Worksheet
    Dim tmpl    As Worksheet
    Dim names() As String
    Dim n       As Long
    Dim i       As Long

    On Error GoTo ErrHandler
    Set ws   = ThisWorkbook.Sheets("Dashboard")
    Set tmpl = ThisWorkbook.Sheets("_Templates")

    ' --- Authoritative template list (auto-generated by setup_xlwings.py) ---
    names = Split("G2 Inlet,Spread Footing,Straight Headwall,Wing Wall,Box Culvert,Retaining Wall,Flat Slab,Drilled Shaft Cage,Concrete Pipe Collar,Slab on Grade,Equipment Pad,Switchboard Pad,Seatwall,Concrete Header,Pipe Encasement,Fuel Foundation,Dual Slab,G2 Expanded Inlet,G2 Inlet Top,G2 Expanded Inlet Top,Junction Structure", ",")
    n = UBound(names) + 1

    ' Write names into _Templates col A rows 1..n (clears old content first)
    tmpl.Range("A1:A50").ClearContents
    For i = 1 To n
        tmpl.Cells(i, 1).Value = names(i - 1)
    Next i

    ' Apply list validation on Dashboard B3 referencing the _Templates range
    With ws.Range("B3").Validation
        .Delete
        .Add Type:=xlValidateList, _
             AlertStyle:=xlValidAlertStop, _
             Formula1:="=_Templates!$A$1:$A$" & n
        .IgnoreBlank = False
        .InCellDropdown = True
        .ShowInput = False
        .ShowError = True
    End With
    Exit Sub

ErrHandler:
    ' Silently ignore — buttons still work even if dropdown fails
End Sub

Sub GenerateDraft()
    xRun "from vistadetail.excel_bridge import on_generate; on_generate()"
End Sub

Sub RefreshInputs()
    xRun "from vistadetail.excel_bridge import on_template_change; on_template_change()"
End Sub

Sub ClearAll()
    xRun "from vistadetail.excel_bridge import on_clear; on_clear()"
End Sub

Sub ExportCSV()
    xRun "from vistadetail.excel_bridge import on_export_csv; on_export_csv()"
End Sub

Sub GenerateDraftNoAI()
    xRun "from vistadetail.excel_bridge import on_generate; on_generate(call_ai=False)"
End Sub

Sub LogCorrections()
    xRun "from vistadetail.excel_bridge import on_log_corrections; on_log_corrections()"
End Sub

Sub ShowConfidence()
    xRun "from vistadetail.excel_bridge import on_show_confidence; on_show_confidence()"
End Sub

Sub RunCutOptimizer()
    xRun "from vistadetail.excel_bridge import on_cut_optimize; on_cut_optimize()"
End Sub

Sub ComposeProject()
    xRun "from vistadetail.excel_bridge import on_compose_project; on_compose_project()"
End Sub

Sub SaveAsGold()
    xRun "from vistadetail.excel_bridge import on_export_gold; on_export_gold()"
End Sub

Sub ClearGold()
    xRun "from vistadetail.excel_bridge import on_clear_gold; on_clear_gold()"
End Sub
"""

# VBA code injected into the Dashboard SHEET module.
# Worksheet_SelectionChange fires when the user clicks any cell — we map the
# button rows (7 and 16) to their macros. This works even without Form Control
# buttons, so clicking the styled cells IS the button click.
_VBA_DASHBOARD_SHEET = """\
Private Sub Worksheet_SelectionChange(ByVal Target As Range)
    ' Row 7 — primary actions
    If Target.Row = 7 Then
        Select Case Target.Column
            Case 1: Application.OnTime Now, "GenerateDraft"
            Case 2: Application.OnTime Now, "RefreshInputs"
            Case 3: Application.OnTime Now, "ClearAll"
            Case 4: Application.OnTime Now, "ExportCSV"
        End Select
    End If
    ' Row 16 — secondary actions
    If Target.Row = 16 Then
        Select Case Target.Column
            Case 1: Application.OnTime Now, "LogCorrections"
            Case 2: Application.OnTime Now, "RunCutOptimizer"
            Case 3: Application.OnTime Now, "ComposeProject"
            Case 4: Application.OnTime Now, "SaveAsGold"
            Case 5: Application.OnTime Now, "ClearGold"
        End Select
    End If
End Sub
"""

# Code injected into the ThisWorkbook module.
# Workbook_Open fires on every open — calls SetupDropdowns so the
# Structure Type dropdown on B3 is always present regardless of
# any openpyxl / Excel repair issues.
_VBA_THIS_WORKBOOK = """\
Private Sub Workbook_Open()
    SetupDropdowns
End Sub
"""


def setup(workbook_path: str = WORKBOOK_PATH) -> None:
    """Wire VBA macros into the workbook via xlwings."""
    try:
        import xlwings as xw
    except ImportError:
        print("ERROR: xlwings not installed. Run: pip install xlwings")
        sys.exit(1)

    wb_path = os.path.abspath(workbook_path)
    if not os.path.exists(wb_path):
        print(f"ERROR: Workbook not found at {wb_path}")
        print("Run first: python -m vistadetail.workbook.create_workbook")
        sys.exit(1)

    print(f"Opening: {wb_path}")
    app = xw.App(visible=True)
    wb = app.books.open(wb_path)

    try:
        # Inject VBA module
        vba_project = wb.api.VBProject
        existing = [c.Name for c in vba_project.VBComponents]

        if "VistaDetail" in existing:
            # Remove old module
            old = vba_project.VBComponents("VistaDetail")
            vba_project.VBComponents.Remove(old)

        new_mod = vba_project.VBComponents.Add(1)   # 1 = vbext_ct_StdModule
        new_mod.Name = "VistaDetail"
        new_mod.CodeModule.AddFromString(_VBA_MODULE)
        print("✓ VBA module 'VistaDetail' injected")

        # Inject SelectionChange handler into the Dashboard sheet module.
        try:
            dash_component = vba_project.VBComponents("Dashboard")
            cm = dash_component.CodeModule
            if cm.CountOfLines > 0:
                cm.DeleteLines(1, cm.CountOfLines)
            cm.AddFromString(_VBA_DASHBOARD_SHEET)
            print("✓ Dashboard SelectionChange handler injected")
        except Exception as e:
            print(f"  ⚠ Dashboard sheet-module inject failed: {e}")
            _wire_dashboard_buttons(wb)

        # Inject Workbook_Open into ThisWorkbook so the dropdown is
        # rebuilt every time the file opens (survives Excel repair).
        try:
            this_wb_component = vba_project.VBComponents("ThisWorkbook")
            cm = this_wb_component.CodeModule
            # Append only if Workbook_Open not already there
            existing_code = cm.Lines(1, max(cm.CountOfLines, 1))
            if "Workbook_Open" not in existing_code:
                cm.AddFromString(_VBA_THIS_WORKBOOK)
                print("✓ Workbook_Open injected into ThisWorkbook")
            else:
                print("✓ Workbook_Open already present in ThisWorkbook")
        except Exception as e:
            print(f"  ⚠ ThisWorkbook inject failed: {e}")

        wb.save()
        print(f"✓ Saved: {wb_path}")

    except Exception as exc:
        print(f"ERROR during setup: {exc}")
        print()
        if "-1743" in str(exc):
            print("═" * 60)
            print("  FIX: macOS blocked Python from controlling Excel.")
            print()
            print("  1. Open:  System Settings → Privacy & Security → Automation")
            print("  2. Find 'Python' or 'Terminal' in the list")
            print("  3. Enable the checkbox next to 'Microsoft Excel'")
            print("  4. Re-run:  python refresh_workbook.py")
            print("═" * 60)
        else:
            print("Manual fallback: open the workbook, press Alt+F11,")
            print("insert a Standard Module, paste this VBA code:\n")
            print(_VBA_MODULE)
            print("\nAlso paste this into the Dashboard sheet module:\n")
            print(_VBA_DASHBOARD_SHEET)
    finally:
        wb.close()
        app.quit()


def _wire_dashboard_buttons(wb) -> None:
    """
    Remove any old Form Control buttons on the Dashboard and recreate all of
    them fresh so they match the current layout (rows 7 and 16).

    Row 7  — primary actions: Generate | Refresh Inputs | Clear All | Export CSV
    Row 16 — secondary:      Log Corrections | Cut Optimizer | Compose | Save Gold | Clear Gold
    """
    ws = wb.sheets["Dashboard"]

    # All buttons: (row, col) → (label, macro_name)
    button_map = {
        # ── Primary row ───────────────────────────────────────────────
        (7, 1): ("GENERATE DRAFT",  "GenerateDraft"),
        (7, 2): ("REFRESH INPUTS",  "RefreshInputs"),
        (7, 3): ("CLEAR ALL",       "ClearAll"),
        (7, 4): ("EXPORT CSV",      "ExportCSV"),
        # ── Secondary row ─────────────────────────────────────────────
        (16, 1): ("LOG CORRECTIONS", "LogCorrections"),
        (16, 2): ("CUT OPTIMIZER",   "RunCutOptimizer"),
        (16, 3): ("COMPOSE PROJECT", "ComposeProject"),
        (16, 4): ("SAVE GOLD",       "SaveAsGold"),
        (16, 5): ("CLEAR GOLD",      "ClearGold"),
    }

    try:
        # ── Remove ALL existing Form Control buttons on this sheet ────
        # (Avoids duplicates when re-running setup after a patch)
        existing_buttons = ws.api.Buttons()
        while existing_buttons.Count > 0:
            existing_buttons.Item(1).Delete()

        # ── Add fresh buttons over the styled cells ───────────────────
        for (row, col), (label, macro) in button_map.items():
            cell   = ws.range((row, col))
            left   = cell.left
            top    = cell.top
            width  = cell.width
            height = cell.height

            btn = ws.api.Buttons().Add(left, top, width, height)
            btn.OnAction = macro
            btn.Characters.Text = label
            # Clear the placeholder cell text so it doesn't show through
            cell.value = None

        print(f"  ✓ {len(button_map)} buttons wired on Dashboard")

    except Exception as exc:
        # On some Mac configurations the AppleScript Buttons API is restricted.
        # Fall back: leave styled cells in place — user can manually assign macros
        # via Developer → Macros → [select macro] → Options → assign to shape.
        print(f"  ⚠ Button wiring failed ({exc})")
        print("    Fallback: styled cells remain. To wire manually:")
        print("    Developer tab → Insert → Button → draw over each cell → assign macro")


def check_addin() -> None:
    """Check whether the xlwings Excel add-in is installed."""
    import subprocess
    result = subprocess.run(
        ["xlwings", "addin", "status"],
        capture_output=True, text=True
    )
    print(result.stdout or result.stderr)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="VistaDetail xlwings setup")
    parser.add_argument("--check-addin", action="store_true",
                        help="Check xlwings add-in status only")
    parser.add_argument("--workbook", default=WORKBOOK_PATH,
                        help="Path to VistaDetail.xlsm")
    args = parser.parse_args()

    if args.check_addin:
        check_addin()
    else:
        setup(args.workbook)
